import { NextPage } from "next";
import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Header } from "../../components/Header";

const About: NextPage = () => {
	return (
		<div>
			<Head>
				<title>About Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<div>
					<h1>Idea DAO</h1>
					<p>
						このサービスは、ユーザーは提案するプロダクトのアイデアに対して、「異能」か「普通」かを投票するDAOです。
						「異能」に選ばれたアイデアはNFTになり、投稿者のアドレスに紐付けられます。
						まずは、自分のアイデアを投稿してみましょう。
					</p>
				</div>
			</main>
		</div>
	);
};

export default About;
